[package]
name = "oyster-attestation-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
anyhow = "1.0.79"
clap = { version = "4.4.6", features = ["derive"] }
derive_more = "0.99.17"
ethers = "2.0.10"
hex = "0.4.3"
libsodium-sys-stable = "1.19.30"
oyster-sdk = "0.4.0"
secp256k1 = "0.28.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_with = "3.3.0"
sha256 = "1.4.0"
thiserror = "1.0.56"
