[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.3", features = ["full"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.16"
