[package]
name = "keygen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
rand_core = { version = "0.6", features = ["getrandom"] }
x25519-dalek = { git="https://github.com/dalek-cryptography/x25519-dalek", branch="release/2.0"}

[profile.release]
strip = true
lto = true
panic = "abort"

