[package]
name = "control-plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7.4"
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws", "rustls"] }
