[package]
name = "raw-proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "raw_proxy"
path = "src/lib.rs"

[[bin]]
name = "ip-to-vsock-raw-incoming"
path = "src/ip_to_vsock_raw_incoming.rs"

[[bin]]
name = "ip-to-vsock-raw-outgoing"
path = "src/ip_to_vsock_raw_outgoing.rs"

[[bin]]
name = "vsock-to-ip-raw-incoming"
path = "src/vsock_to_ip_raw_incoming.rs"

[[bin]]
name = "vsock-to-ip-raw-outgoing"
path = "src/vsock_to_ip_raw_outgoing.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.73"
libc = "0.2.147"
nfq = "0.2.5"
socket2 = { version = "0.5.3", features = ["all"] }
thiserror = "1.0.47"
clap = { version = "4.4.5", features = ["derive"] }

[profile.release]
strip = true
lto = true
panic = "abort"
