[package]
name = "keygen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
libsodium-sys-stable = "1.19.27"

[profile.release]
strip = true
lto = true
panic = "abort"

