[package]
name = "raw-proxy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ip-to-vsock-raw"
path = "src/ip_to_vsock_raw.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.5.3", features = ["all"] }
