[package]
name = "raw-proxy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ip-to-vsock-raw"
path = "src/ip_to_vsock_raw.rs"

[[bin]]
name = "vsock-to-ip-raw"
path = "src/vsock_to_ip_raw.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.73"
socket2 = { version = "0.5.3", features = ["all"] }
