[package]
name = "control-plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7.4"
aws-config = "0.51.0"
aws-types = "0.51.0"
aws-sdk-ec2 = "0.21.0"
ssh2 = "0.9.3"
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws", "rustls"] }
serde_json = "1.0.88"
reqwest = "0.11.13"
clap = { version = "4.0.29", features = ["derive"] }
whoami = "0.2.0"
async-trait = "0.1.51"