[workspace]
resolver = "2"
members = ["host", "methods"]

[workspace.package]
license = "AGPL-3.0-or-later"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
